- rename header
- combined the residence place to one column 
- seperate the often used mode of transport, data input the will be 1/0
- clear missing data point (~51/374)

In [221]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", 300)

In [222]:
df = pd.read_excel ('Overall Mobility Transport Demand Survey(1-374).xlsx')
print (df)

      ID          Start time     Completion time      Email  Name  \
0      4 2021-09-01 00:38:08 2021-09-01 00:48:28  anonymous   NaN
1      5 2021-09-01 00:44:47 2021-09-01 01:01:51  anonymous   NaN
2     12 2021-09-01 09:55:31 2021-09-01 10:06:14  anonymous   NaN
3     13 2021-09-01 10:01:29 2021-09-01 10:06:21  anonymous   NaN
4     14 2021-09-01 10:00:35 2021-09-01 10:06:31  anonymous   NaN
..   ...                 ...                 ...        ...   ...
369  353 2021-09-07 02:08:18 2021-09-07 02:08:46  anonymous   NaN
370  373 2021-09-08 22:00:43 2021-09-08 22:17:13  anonymous   NaN
371  376 2021-09-12 13:30:15 2021-09-12 14:19:58  anonymous   NaN
372  374 2021-09-10 13:02:44 2021-09-10 13:03:04  anonymous   NaN
373  375 2021-09-10 13:03:19 2021-09-10 13:03:39  anonymous   NaN

    What is your age? What is your gender?  \
0             22 - 25               Female
1             22 - 25               Female
2             22 - 25                 Male
3             18 - 21               Female
4             22 - 25               Female
..                ...                  ...
369           18 - 21               Female
370           22 - 25               Female
371           22 - 25               Female
372           26 - 29                 Male
373           26 - 29                 Male

    What is your current employment status?  \
0                        Full-time Student;
1     Employed Part-time;Full-time Student;
2                        Full-time Student;
3                        Full-time Student;
4                                 Contract;
..                                      ...
369                      Full-time Student;
370                      Full-time Student;
371                      Full-time Student;
372                     Employed Full-time;
373                     Employed Full-time;

    What is your monthly income range? Are you a tertiary student?  ...  \
0                           Below $500                         Yes  ...
1                           Below $500                         Yes  ...
2                           Below $500                         Yes  ...
3                           Below $500                         Yes  ...
4                    Prefer not to say                         Yes  ...
..                                 ...                         ...  ...
369                         Below $500                          No  ...
370                         Below $500                         Yes  ...
371                         Below $500                         Yes  ...
372                    $2,001 - $3,000                          No  ...
373                    $2,001 - $3,000                          No  ...

          Customer Service                   Cost             Comfort  \
0                  Neutral  Somewhat dissatisfied  Somewhat satisfied
1    Somewhat dissatisfied  Somewhat dissatisfied  Somewhat satisfied
2       Somewhat satisfied                Neutral  Somewhat satisfied
3       Somewhat satisfied     Somewhat satisfied  Somewhat satisfied
4                  Neutral                Neutral             Neutral
..                     ...                    ...                 ...
369                    NaN                    NaN                 NaN
370     Somewhat satisfied     Somewhat satisfied  Somewhat satisfied
371     Somewhat satisfied     Somewhat satisfied  Somewhat satisfied
372                    NaN                    NaN                 NaN
373                    NaN                    NaN                 NaN

            Reliability Service Information      Overall Rating  \
0    Somewhat satisfied             Neutral             Neutral
1    Somewhat satisfied  Somewhat satisfied             Neutral
2        Very satisfied  Somewhat satisfied  Somewhat satisfied
3    Somewhat satisfied  Somewhat satisfied  Somewhat satisfied
4               Neutral             Neutral             Neutral
..                  ...                 ...                 ...
369                 NaN                 NaN                 NaN
370      Very satisfied             Neutral      Very satisfied
371  Somewhat satisfied  Somewhat satisfied  Somewhat satisfied
372                 NaN                 NaN                 NaN
373                 NaN                 NaN                 NaN

    What are your opinions on ComfortDelGro?  \
0                        Just a taxi company
1                                        NaN
2                    Rides are really comfy
3                                        NaN
4                                        NaN
..                                       ...
369                                      NaN
370                        Easily available
371                         Traditional taxi
372                                      NaN
373                                      NaN

    How do you think ComfortDelGro can improve their services?  \
0                  Not very sure donâ€™t take them often
1                                                  NaN
2      Lowering their price to compete with grab/gojek
3                                                  NaN
4                                                  NaN
..                                                 ...
369                                                NaN
370                           Promotion very confusing
371                          Improve their online app
372                                                NaN
373                                                NaN

    Which of the following options would incentivize you to use ComfortDelGro's Rent-A-Car service?  \
0    More locations to rent from;Competitive prices...
1    More locations to rent from;Competitive prices...
2         More locations to rent from;Promotion codes;
3                                  Competitive prices;
4                                                  NaN
..                                                 ...
369                                                NaN
370  More locations to rent from;Competitive prices...
371                                           neither;
372                                                NaN
373                                                NaN

    If you wish to participate in the lucky draw, please fill in your email address below.
0                                                  NaN
1                     shermin.tan.2018@scis.smu.edu.sg
2                             shawnangweijie@gmail.com
3                           isham.2020@scis.smu.edu.sg
4                         lauratriciareyes@hotmail.com
..                                                 ...
369                                                NaN
370                                danniikoh@gmail.com
371                                                NaN
372                                                NaN
373                                                NaN

[374 rows x 100 columns]

In [223]:
demographic_df = df.iloc[:, 5:17]
demographic_df.columns = ['age', 'gender', 'employment_status', 'montly_income','tertiary_student', 'instituition', 'region', 'east', 'north', 'north-east', 'west','central']

demographic_df[['east', 'north', 'north-east', 'west','central']] = demographic_df[['east', 'north', 'north-east', 'west','central']].fillna('')
demographic_df['location']=demographic_df['east'].astype(str)+demographic_df['north'].astype(str)+demographic_df['north-east'].astype(str)+demographic_df['west'].astype(str)+demographic_df['central'].astype(str)
demographic_df = demographic_df.drop(columns=['east', 'north', 'north-east', 'west','central'])

demographic_df['employment_status'] = demographic_df['employment_status'].str[:-1]
lst_col = 'employment_status'
demographic_df = demographic_df.assign(**{lst_col:demographic_df[lst_col].str.split(';')})
demographic_df.employment_status = demographic_df.employment_status.fillna('')
employment_status_df = pd.DataFrame(demographic_df.employment_status.values.tolist()).add_prefix('employment_status_')
demographic_df = demographic_df.merge(employment_status_df, left_index=True, right_index=True)
demographic_df.drop('employment_status', axis=1, inplace=True)

demographic_df.head()

,age,gender,montly_income,tertiary_student,instituition,region,location,employment_status_0,employment_status_1
0,22 - 25,Female,Below $500,Yes,SMU,North,Yishun,Full-time Student,None
1,22 - 25,Female,Below $500,Yes,SMU,West,Bukit Batok,Employed Part-time,Full-time Student
2,22 - 25,Male,Below $500,Yes,SIT,West,Bukit Batok,Full-time Student,None
3,18 - 21,Female,Below $500,Yes,SMU,East,Tampines,Full-time Student,None
4,22 - 25,Female,Prefer not to say,Yes,SIM,East,Prefer not to say,Contract,None

In [249]:
mot_df = df.iloc[:, 17:27]
mot_df.columns = ['frequently_used_mot', 'frequency_mot', 'preferred_mot', 'reason_least_preferred_mot','circ_least_preferred_mot', 'factors_mot_ranking', 'overall_avg_spending', 'research', 'comfortable', 'explore']

In [250]:
col_name = ['frequently_used_mot', 'preferred_mot', 'factors_mot_ranking']

for i in col_name:
    mot_df[i] = mot_df[i].str[:-1]
    mot_df[i] = mot_df[i].fillna('')
    mot_df[i] = [x.split(';') for x in mot_df[i]]

In [251]:
mot_df

,frequently_used_mot,frequency_mot,preferred_mot,reason_least_preferred_mot,circ_least_preferred_mot,factors_mot_ranking,overall_avg_spending,research,comfortable,explore
0,"[MRT, Bus]",Once a week,"[Ride-hailing services, MRT, BusÂ , Taxi, Car r...",Expensive to rent a car. Singapore too hot to ...,When there is no choice,"[Physical Accessibility, Price, Safety, Reliab...",$50-$100,9.0,9.0,1.0
1,"[Bus, MRT, Taxi, Ride-hailing services]",3 - 4 days a week,"[Ride-hailing services, Taxi, BusÂ , MRT, Other...",Car Rentals are expensive. Destination too far...,If it's nearby or if car rentals are the cheap...,"[Travel Time, Price, Waiting Time, Comfort, Ph...",More than $150,6.0,3.0,4.0
2,"[Bus, MRT, Ride-hailing services]",Daily,"[BusÂ , MRT, Ride-hailing services, Others: Cyc...",The price point,In dire situation where I canâ€™t get grab/gojek...,"[Price, Waiting Time, Travel Time, Reliability...",$50-$100,8.0,7.0,6.0
3,"[Bus, MRT]",Daily,"[MRT, BusÂ , Others: Cycle, Walk, Drive, Taxi, ...",Expensive,Running late,"[Price, Travel Time, Comfort, Waiting Time, Ph...",$50-$100,10.0,10.0,10.0
4,"[MRT, Bus]",3 - 4 days a week,"[BusÂ , MRT, Taxi, Ride-hailing services, Car r...",NaN,NaN,"[Price, Travel Time, Comfort, Physical Accessi...",$50-$100,7.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...
369,[],NaN,[],NaN,NaN,[],NaN,NaN,NaN,NaN
370,"[Bus, MRT, Ride-hailing services]",5 - 6 days a week,"[Ride-hailing services, Taxi, MRT, BusÂ , Other...",Other: Less convenient\nCar Rental: Expensive ...,Other: if the distance is short and Iâ€™m not in...,"[Travel Time, Price, Physical Accessibility, R...",$50-$100,8.0,6.0,6.0
371,"[MRT, Bus]",3 - 4 days a week,"[MRT, BusÂ , Taxi, Others: Cycle, Walk, Drive, ...",NaN,NaN,"[Price, Physical Accessibility, Travel Time, R...",$50-$100,5.0,3.0,1.0
372,[],NaN,[],NaN,NaN,[],NaN,NaN,NaN,NaN
373,[],NaN,[],NaN,NaN,[],NaN,NaN,NaN,NaN

In [252]:
bus_df = df.iloc[:, 27:37]
bus_df.columns = ['frequency_bus', 'waiting_time_bus', 'reason_bus', 'affordable_bus','accesible_bus', 'safe_bus', 'prevent_bus', 'chartered_bus', 'occasion_chartered_bus', 'price_chartered_bus']

In [253]:
col_name = ['reason_bus', 'prevent_bus']

for i in col_name:
    bus_df[i] = bus_df[i].str[:-1]
    bus_df[i] = bus_df[i].fillna('')
    bus_df[i] = [x.split(';') for x in bus_df[i]]

In [254]:
bus_df

,frequency_bus,waiting_time_bus,reason_bus,affordable_bus,accesible_bus,safe_bus,prevent_bus,chartered_bus,occasion_chartered_bus,price_chartered_bus
0,None,Less than 10 minutes,"[When travelling to the nearby MRT Stations, D...",Agree,Strongly Agree,Strongly Agree,"[Bulky items, Long waiting time, Long travel t...",No,NaN,I don't know
1,2-4 times a week,10-20 minutes,"[When travelling to the nearby MRT Stations, D...",Agree,Agree,Agree,"[Bulky items, Too crowded]",No,Going on a trip to somewhere with many people ...,$101 - $120
2,Daily,Less than 10 minutes,"[When travelling to the nearby MRT Stations, D...",Agree,Agree,Agree,"[Long waiting time, Bulky items]",No,NaN,< $100
3,2-4 times a week,Less than 10 minutes,"[When travelling to the nearby MRT Stations, D...",Agree,Agree,Agree,"[Long waiting time, Bulky items, Too crowded]",No,NaN,< $100
4,2-4 times a week,Less than 10 minutes,[Direct to recreation destination (e.g. food c...,Neutral,Neutral,Neutral,"[Long travel time, Too crowded]",No,NaN,I don't know
...,...,...,...,...,...,...,...,...,...,...
369,NaN,NaN,[],NaN,NaN,NaN,[],NaN,NaN,NaN
370,5-6 times a week,Less than 10 minutes,"[When travelling to the nearby MRT Stations, D...",Neutral,Strongly Agree,Agree,"[Long waiting time, Long travel time, Too crow...",No,When a lot of people travelling to the same lo...,I don't know
371,2-4 times a week,10-20 minutes,"[When travelling to the nearby MRT Stations, D...",Disagree,Agree,Agree,"[Bulky items, Too crowded]",No,NaN,< $100
372,NaN,NaN,[],NaN,NaN,NaN,[],NaN,NaN,NaN
373,NaN,NaN,[],NaN,NaN,NaN,[],NaN,NaN,NaN

In [258]:
mrt_df = df.iloc[:, 37:46]
mrt_df.columns = ['frequency_mrt', 'spend_mrt', 'reason_mrt', 'mrt_lines','affordable_mrt', 'accessible_mrt', 'waiting_mrt', 'safe_mrt', 'prevent_mrt']

In [259]:
col_name = ['reason_mrt', 'mrt_lines', 'prevent_mrt']

for i in col_name:
    mrt_df[i] = mrt_df[i].str[:-1]
    mrt_df[i] = mrt_df[i].fillna('')
    mrt_df[i] = [x.split(';') for x in mrt_df[i]]

In [260]:
mrt_df

,frequency_mrt,spend_mrt,reason_mrt,mrt_lines,affordable_mrt,accessible_mrt,waiting_mrt,safe_mrt,prevent_mrt
0,3-4 days per week,45-60 mins,"[To get to work/school, ToÂ directly get to rec...",[North-South Line (Red Line)],Agree,Strongly Agree\n,Strongly Agree\n,Agree,[When Iâ€™m late and rushing to get to my destin...
1,One day per week,30-45 mins,"[To get to work/school, ToÂ directly get to rec...","[Downtown Line (Blue Line), North-South Line (...",Agree,Agree,Agree,Agree,"[Bulky items, Long travel time, Too crowded]"
2,5-6 days per week,30-45 mins,"[To get to work/school, ToÂ directly get to rec...","[Downtown Line (Blue Line), East-West Line (Gr...",Agree,Agree,Agree,Agree,[Long travel time]
3,5-6 days per week,30-45 mins,"[To get to work/school, ToÂ directly get to rec...",[Downtown Line (Blue Line)],Agree,Agree,Agree,Agree,[Too crowded]
4,3-4 days per week,30-45 mins,[To get to work/school],[East-West Line (Green Line)],Neutral,Neutral,Neutral,Neutral,[Long travel time]
...,...,...,...,...,...,...,...,...,...
369,NaN,NaN,[],[],NaN,NaN,NaN,NaN,[]
370,5-6 days per week,45-60 mins,"[To get to the relevant bus stop, To get to wo...",[North-South Line (Red Line)],Neutral,Strongly Agree\n,Disagree,Strongly Agree\n,"[Long travel time, Long wait time, Too crowded..."
371,3-4 days per week,30-45 mins,"[To get to the relevant bus stop, ToÂ directly ...","[Downtown Line (Blue Line), East-West Line (Gr...",Agree,Agree,Agree,Disagree,[nil]
372,NaN,NaN,[],[],NaN,NaN,NaN,NaN,[]
373,NaN,NaN,[],[],NaN,NaN,NaN,NaN,[]

In [261]:
taxi_df = df.iloc[:, 46:57]
taxi_df.columns = ['frequency_taxi', 'waiting_time_taxi', 'way_hail', 'reason_taxi', 'preference_rank_taxi', 'affordable_taxi', 'accessible_taxi', 'safe_taxi', 'customer_service_taxi', 'difficulties_taxi', 'prevent_taxi']

In [262]:
col_name = ['way_hail', 'reason_taxi', 'preference_rank_taxi', 'prevent_taxi']

for i in col_name:
    taxi_df[i] = taxi_df[i].str[:-1]
    taxi_df[i] = taxi_df[i].fillna('')
    taxi_df[i] = [x.split(';') for x in taxi_df[i]]

In [263]:
taxi_df

,frequency_taxi,waiting_time_taxi,way_hail,reason_taxi,preference_rank_taxi,affordable_taxi,accessible_taxi,safe_taxi,customer_service_taxi,difficulties_taxi,prevent_taxi
0,Never,5-10 mins,"[Flag down, Use grab app ]","[When it is more accessible, When there is a p...","[ComfortDelgro, Trans-Cab, SMRT Taxi, Premier ...",Neutral,Neutral,Agree,Neutral,Yes when it is late at night. From SMU back to...,"[Too costly, Private hire is cheaper]"
1,Once a week,5-10 mins,[Online/In-app],"[When there is a promotion, When it is easy to...","[ComfortDelgro, Trans-Cab, CityCab, Prime Taxi...",Disagree,Disagree,Agree,Agree,"Peak hours, CBD or secluded areas","[Too costly, Private hire is cheaper, Long wai..."
2,Never,Less than 5 mins,"[Online/In-app, Flag down]",[When the price is cheaper ],"[ComfortDelgro, Trans-Cab, CityCab, SMRT Taxi,...",Disagree,Agree,Strongly Agree,Agree,NaN,"[Too costly, Private hire is cheaper]"
3,Never,5-10 mins,"[Flag down, Online/In-app]","[When it is more accessible, When there is a p...","[ComfortDelgro, SMRT Taxi, Premier Taxi, Trans...",Agree,Agree,Agree,Strongly Agree,NIL,[Too costly]
4,Never,5-10 mins,[Online/In-app],[When it is more convenient],"[Premier Taxi, ComfortDelgro, Trans-Cab, CityC...",Neutral,Neutral,Neutral,Neutral,-,[Too costly]
...,...,...,...,...,...,...,...,...,...,...,...
369,NaN,NaN,[],[],[],NaN,NaN,NaN,NaN,NaN,[]
370,Once a week,5-10 mins,[Online/In-app],"[When Iâ€™m rushing , When it is more convenient]","[ComfortDelgro, SMRT Taxi, Trans-Cab, CityCab,...",Disagree,Agree,Agree,Neutral,When I travel with my pet (small dog),[Too costly]
371,Never,5-10 mins,[Online/In-app],[When it is more convenient],"[ComfortDelgro, Trans-Cab, SMRT Taxi, Premier ...",Disagree,Disagree,Agree,Disagree,NaN,[Too costly]
372,NaN,NaN,[],[],[],NaN,NaN,NaN,NaN,NaN,[]
373,NaN,NaN,[],[],[],NaN,NaN,NaN,NaN,NaN,[]

In [278]:
ride_hailing_df = df.iloc[:, 57:67]
ride_hailing_df.columns = ['frequency_ride_hailing', 'reason_ride_hailing', 'ride_hailing_type', 'preference_rank_ride_hailing', 'reason_ride_hailing_company', 'affordable_ride_hailing', 'safe_ride_hailing', 'customer_service_ride_hailing', 'difficulties_ride_hailing', 'prevent_ride_hailing']

In [279]:
col_name = ['reason_ride_hailing', 'ride_hailing_type', 'preference_rank_ride_hailing', 'reason_ride_hailing_company', 'prevent_ride_hailing']

for i in col_name:
    #ride_hailing_df[i].astype(str)
    ride_hailing_df[i] = ride_hailing_df[i].str[:-1]
    ride_hailing_df[i] = ride_hailing_df[i].fillna('')
    ride_hailing_df[i] = [x.split(';') for x in ride_hailing_df[i]]

In [280]:
ride_hailing_df

,frequency_ride_hailing,reason_ride_hailing,ride_hailing_type,preference_rank_ride_hailing,reason_ride_hailing_company,affordable_ride_hailing,safe_ride_hailing,customer_service_ride_hailing,difficulties_ride_hailing,prevent_ride_hailing
0,Once a week,"[When there is a promotion, When it is more ac...","[Grab, Gojek]","[Grab, Gojek, Ryde, Comfort DelGro, Others, Ta...","[Familiar with the software, easy user interfac]",Agree,Agree,Neutral,Nil,"[Poor driving, Long wait time]"
1,3-4 days a week,"[When it is easy to book, When there is a prom...","[Grab, Gojek, ComfortDelGro, Ryde]","[Grab, Comfort DelGro, Gojek, Ryde, Tada Mobil...",[More affordable and competitive pricing.],Neutral,Agree,Strongly Agree\n,"Peak hours, CBD and secluded areas","[Poor driving, Poor customer service, Too costly]"
2,Once a week,"[When it is easy to book, When there is a prom...","[Grab, Gojek, ComfortDelGro]","[Grab, Gojek, Comfort DelGro, Ryde, Tada Mobil...",[Because of ongoing promotion],Neutral,Agree,Strongly Agree\n,NaN,"[Poor driving, Poor customer service]"
3,None,"[When there is a promotion, When it is more co...",[Grab],"[Grab, Comfort DelGro, Gojek, Ryde, Tada Mobil...",[],Agree,Neutral,Agree,NaN,"[Too costly, Poor driving, Poor customer service]"
4,None,[When it is more convenient],[Grab],"[Grab, Gojek, Ryde, Comfort DelGro, Tada Mobil...",[],Neutral,Neutral,Neutral,NaN,[Too costly]
...,...,...,...,...,...,...,...,...,...,...
369,NaN,[],[],[],[],NaN,NaN,NaN,NaN,[]
370,None,"[When Iâ€™m rushing, When it is more convenient]","[Grab, ComfortDelGro, Ryde]","[Comfort DelGro, Ryde, Grab, Gojek, Tada Mobil...",[Promotion & Convenienc],Strongly Disagree\n,Neutral,Neutral,Yes. Price surge like mad,[Too costly]
371,None,[When it is more convenient],[ComfortDelGro],"[Comfort DelGro, Gojek, Grab, Ryde, Tada Mobil...",[],Disagree,Disagree,Disagree,NaN,[Too costly]
372,NaN,[],[],[],[],NaN,NaN,NaN,NaN,[]
373,NaN,[],[],[],[],NaN,NaN,NaN,NaN,[]

In [281]:
car_rental_df = df.iloc[:, 67:87]
car_rental_df.columns = ['own_driving_license', 'rent_before', 'preference_rank_rental_car', 'reason_rental_car_company', 'frequency_rental','duration_rental', 'reason_rental_car', 'difficulties_rental_car', 'difficulties_reason_rental_car', 'convenient_rental_car', 'convenient_reason_rental_car', 'affordable_rental_car', 'reasonable_rental_car', 'type_rental_car', 'perception_rental_car', 'max_price_rental_car', 'biz_model_rental', 'biz_model_reason_rental', 'biz_model_important_rental', 'prevent_rental']

In [282]:
col_name = ['preference_rank_rental_car', 'reason_rental_car_company', 'reason_rental_car', 'type_rental_car', 'biz_model_rental', 'biz_model_reason_rental', 'prevent_rental']

for i in col_name:
    #ride_hailing_df[i].astype(str)
    car_rental_df[i] = car_rental_df[i].str[:-1]
    car_rental_df[i] = car_rental_df[i].fillna('')
    car_rental_df[i] = [x.split(';') for x in car_rental_df[i]]

In [283]:
car_rental_df

,own_driving_license,rent_before,preference_rank_rental_car,reason_rental_car_company,frequency_rental,duration_rental,reason_rental_car,difficulties_rental_car,difficulties_reason_rental_car,convenient_rental_car,convenient_reason_rental_car,affordable_rental_car,reasonable_rental_car,type_rental_car,perception_rental_car,max_price_rental_car,biz_model_rental,biz_model_reason_rental,biz_model_important_rental,prevent_rental
0,Yes,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,"[Tribecar, Grabcar Rental, BlueSG]",NaN,$3.01 - $5,[Free-floating],[Convenience],6.0,"[Inconvenient Pickup Locations, Costly, Safety..."
1,Yes,Yes,"[BlueSG, No preference, GetGo, Tribecar, Lion...",[Convenient],Once a year,< 1 hour,"[Convenience, Occasions, Too costly to own a c...",No,NaN,No,Near Shopping Malls or MRT stations or Estates...,Strongly disagree,Disagree,[],NaN,NaN,[Free-floating],"[Convenience, Cost]",8.0,"[Inconvenient Pickup Locations, Costly, Safety..."
2,Yes,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,"[BlueSG, GetGO, Tribecar, Grabcar Rental]",NaN,$5.01 - $7,[Station-based],"[Cost, Convenience]",6.0,"[Inconvenient Pickup Locations, Costly, Insura..."
3,No,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[BlueSG],NaN,$3.01 - $5,[Free-floating],[Convenience],5.0,"[Costly, Age Restrictions]"
4,No,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[BlueSG],NaN,< $3,"[Station-based, Free-floating]",[Cost],5.0,[Costly]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,NaN,NaN,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,[],[],NaN,[]
370,No,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[Tribecar],NaN,< $3,[Station-based],"[Cost, Convenience, Reliability]",5.0,"[Inconvenient Pickup Locations, Costly]"
371,No,No,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,"[BlueSG, Tribecar, Grabcar Rental]",NaN,$3.01 - $5,[Free-floating],[Convenience],7.0,[Inconvenient Pickup Locations]
372,NaN,NaN,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,[],[],NaN,[]
373,NaN,NaN,[],[],NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,[],[],NaN,[]

In [289]:
perception_cdg_df = df.iloc[:, 87:99]
perception_cdg_df.columns = ['aware_cdg', 'used_cdg', 'accessibility_cdg', 'cs_cdg', 'cost_cdg', 'comfort_cdg', 'reliability_cdg', 'info_cdg', 'overall_rating_cdg', 'perception_cdg', 'improvement_cdg', 'incentives_cdg']

In [290]:
col_name = ['aware_cdg', 'used_cdg', 'incentives_cdg']

for i in col_name:
    #ride_hailing_df[i].astype(str)
    perception_cdg_df[i] = perception_cdg_df[i].str[:-1]
    perception_cdg_df[i] = perception_cdg_df[i].fillna('')
    perception_cdg_df[i] = [x.split(';') for x in perception_cdg_df[i]]

In [291]:
perception_cdg_df

,aware_cdg,used_cdg,accessibility_cdg,cs_cdg,cost_cdg,comfort_cdg,reliability_cdg,info_cdg,overall_rating_cdg,perception_cdg,improvement_cdg,incentives_cdg
0,[Taxi],[Taxi],Somewhat satisfied,Neutral,Somewhat dissatisfied,Somewhat satisfied,Somewhat satisfied,Neutral,Neutral,Just a taxi company,Not very sure donâ€™t take them often,"[More locations to rent from, Competitive pric..."
1,[Taxi],[Taxi],Neutral,Somewhat dissatisfied,Somewhat dissatisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Neutral,NaN,NaN,"[More locations to rent from, Competitive pric..."
2,[Taxi],[Taxi],Somewhat satisfied,Somewhat satisfied,Neutral,Somewhat satisfied,Very satisfied,Somewhat satisfied,Somewhat satisfied,Rides are really comfy,Lowering their price to compete with grab/gojek,"[More locations to rent from, Promotion codes]"
3,[Taxi],[Taxi],Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,NaN,NaN,[Competitive prices]
4,[Taxi],[Taxi],Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
369,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
370,[Taxi],[Taxi],Neutral,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Very satisfied,Neutral,Very satisfied,Easily available,Promotion very confusing,"[More locations to rent from, Competitive pric..."
371,[Taxi],[Taxi],Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Traditional taxi,Improve their online app,[neither]
372,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
373,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]

In [292]:
df = pd.concat([demographic_df, mot_df, bus_df, mrt_df, taxi_df, ride_hailing_df, perception_cdg_df], axis=1)
df

,age,gender,montly_income,tertiary_student,instituition,region,location,employment_status_0,employment_status_1,frequently_used_mot,...,accessibility_cdg,cs_cdg,cost_cdg,comfort_cdg,reliability_cdg,info_cdg,overall_rating_cdg,perception_cdg,improvement_cdg,incentives_cdg
0,22 - 25,Female,Below $500,Yes,SMU,North,Yishun,Full-time Student,None,"[MRT, Bus]",...,Somewhat satisfied,Neutral,Somewhat dissatisfied,Somewhat satisfied,Somewhat satisfied,Neutral,Neutral,Just a taxi company,Not very sure donâ€™t take them often,"[More locations to rent from, Competitive pric..."
1,22 - 25,Female,Below $500,Yes,SMU,West,Bukit Batok,Employed Part-time,Full-time Student,"[Bus, MRT, Taxi, Ride-hailing services]",...,Neutral,Somewhat dissatisfied,Somewhat dissatisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Neutral,NaN,NaN,"[More locations to rent from, Competitive pric..."
2,22 - 25,Male,Below $500,Yes,SIT,West,Bukit Batok,Full-time Student,None,"[Bus, MRT, Ride-hailing services]",...,Somewhat satisfied,Somewhat satisfied,Neutral,Somewhat satisfied,Very satisfied,Somewhat satisfied,Somewhat satisfied,Rides are really comfy,Lowering their price to compete with grab/gojek,"[More locations to rent from, Promotion codes]"
3,18 - 21,Female,Below $500,Yes,SMU,East,Tampines,Full-time Student,None,"[Bus, MRT]",...,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,NaN,NaN,[Competitive prices]
4,22 - 25,Female,Prefer not to say,Yes,SIM,East,Prefer not to say,Contract,None,"[MRT, Bus]",...,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,18 - 21,Female,Below $500,No,NaN,NaN,,Full-time Student,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
370,22 - 25,Female,Below $500,Yes,SMU,North,Woodlands,Full-time Student,None,"[Bus, MRT, Ride-hailing services]",...,Neutral,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Very satisfied,Neutral,Very satisfied,Easily available,Promotion very confusing,"[More locations to rent from, Competitive pric..."
371,22 - 25,Female,Below $500,Yes,NUS,West,Clementi,Full-time Student,None,"[MRT, Bus]",...,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Somewhat satisfied,Traditional taxi,Improve their online app,[neither]
372,26 - 29,Male,"$2,001 - $3,000",No,NaN,NaN,,Employed Full-time,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
373,26 - 29,Male,"$2,001 - $3,000",No,NaN,NaN,,Employed Full-time,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]